/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    documentos: Documento;
    empresas: Empresa;
    proyectos: Proyecto;
    noticias: Noticia;
    'biblioteca-recursos': BibliotecaRecurso;
    'educacion-programas': EducacionPrograma;
    'agenda-eventos': AgendaEvento;
    cotizaciones: Cotizacione;
    'cotizacion-updates': CotizacionUpdate;
    'proyecto-drafts': ProyectoDraft;
    'consultas-proveedores': ConsultasProveedore;
    'consultas-contacto': ConsultasContacto;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documentos: DocumentosSelect<false> | DocumentosSelect<true>;
    empresas: EmpresasSelect<false> | EmpresasSelect<true>;
    proyectos: ProyectosSelect<false> | ProyectosSelect<true>;
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    'biblioteca-recursos': BibliotecaRecursosSelect<false> | BibliotecaRecursosSelect<true>;
    'educacion-programas': EducacionProgramasSelect<false> | EducacionProgramasSelect<true>;
    'agenda-eventos': AgendaEventosSelect<false> | AgendaEventosSelect<true>;
    cotizaciones: CotizacionesSelect<false> | CotizacionesSelect<true>;
    'cotizacion-updates': CotizacionUpdatesSelect<false> | CotizacionUpdatesSelect<true>;
    'proyecto-drafts': ProyectoDraftsSelect<false> | ProyectoDraftsSelect<true>;
    'consultas-proveedores': ConsultasProveedoresSelect<false> | ConsultasProveedoresSelect<true>;
    'consultas-contacto': ConsultasContactoSelect<false> | ConsultasContactoSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-theme': SiteTheme;
  };
  globalsSelect: {
    'site-theme': SiteThemeSelect<false> | SiteThemeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nombreCompleto?: string | null;
  role: 'admin' | 'proveedor' | 'cliente';
  onboarded?: boolean | null;
  profileType?: ('empresa' | 'particular' | 'inversor' | 'productor' | 'estudiante') | null;
  telefono?: string | null;
  organizacion?: string | null;
  pais?: string | null;
  provincia?: string | null;
  ciudad?: string | null;
  intereses?:
    | {
        interes: string;
        id?: string | null;
      }[]
    | null;
  notas?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos".
 */
export interface Documento {
  id: number;
  nombre: string;
  empresa?: (number | null) | Empresa;
  subidoPor?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "empresas".
 */
export interface Empresa {
  id: number;
  nombre: string;
  slug: string;
  sector?: string | null;
  descripcion?: string | null;
  ubicacion?: string | null;
  tipoProveedor?: ('empresa' | 'productor' | 'industrial' | 'profesional') | null;
  servicios?:
    | {
        servicio: string;
        id?: string | null;
      }[]
    | null;
  serviciosDetalle?:
    | {
        servicio: string;
        detalle?: string | null;
        id?: string | null;
      }[]
    | null;
  productos?:
    | {
        nombre: string;
        descripcion?: string | null;
        imagen?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  logo?: (number | null) | Media;
  galeria?: (number | Media)[] | null;
  sitioWeb?: string | null;
  anioFundacion?: number | null;
  empleados?: string | null;
  estado: 'borrador' | 'en_revision' | 'publicado' | 'archivado';
  publicada?: boolean | null;
  user?: (number | null) | User;
  contacto?: string | null;
  telefono?: string | null;
  whatsapp?: string | null;
  documentos?: (number | Documento)[] | null;
  consentimientos?: {
    terminosAceptados?: boolean | null;
    comunicacionesAceptadas?: boolean | null;
    version?: string | null;
    fechaConsentimiento?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proyectos".
 */
export interface Proyecto {
  id: number;
  titulo: string;
  slug: string;
  resumen?: string | null;
  descripcion?: string | null;
  categoria?: ('Vivienda' | 'Comercial' | 'Institucional' | 'Industrial' | 'Turismo') | null;
  ubicacion?: string | null;
  anio?: number | null;
  arquitecto?: string | null;
  constructora?: string | null;
  sistemaConstructivo?: string | null;
  impactoCarbono?: string | null;
  materiales?:
    | {
        material: string;
        id?: string | null;
      }[]
    | null;
  empresas?: (number | Empresa)[] | null;
  portada?: (number | null) | Media;
  galeria?: (number | Media)[] | null;
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: number;
  titulo: string;
  slug: string;
  resumen?: string | null;
  contenido?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  categoria?: string | null;
  autor?: string | null;
  imagen?: (number | null) | Media;
  destacada?: boolean | null;
  publicada?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "biblioteca-recursos".
 */
export interface BibliotecaRecurso {
  id: number;
  titulo: string;
  categoria?: string | null;
  archivo: number | Media;
  paginas?: number | null;
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educacion-programas".
 */
export interface EducacionPrograma {
  id: number;
  titulo: string;
  descripcion?: string | null;
  modalidad?: ('presencial' | 'virtual' | 'hibrido') | null;
  duracion?: string | null;
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agenda-eventos".
 */
export interface AgendaEvento {
  id: number;
  titulo: string;
  fecha: string;
  lugar?: string | null;
  descripcion?: string | null;
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cotizaciones".
 */
export interface Cotizacione {
  id: number;
  empresa: number | Empresa;
  solicitante: number | User;
  tipoConsulta: 'producto' | 'servicio' | 'proyecto';
  referencia?: string | null;
  descripcion: string;
  cantidad?: string | null;
  plazo?: string | null;
  ubicacion?: string | null;
  presupuesto?: string | null;
  solicitanteNombre: string;
  solicitanteEmail: string;
  solicitanteTelefono?: string | null;
  solicitanteEmpresa?: string | null;
  estado: 'enviada' | 'en_revision' | 'respondida' | 'cerrada' | 'cancelada';
  respuesta?: string | null;
  respondidaAt?: string | null;
  presupuestoMonto?: number | null;
  presupuestoMoneda?: ('ARS' | 'USD' | 'EUR') | null;
  presupuestoValidezDias?: number | null;
  presupuestoPlazo?: string | null;
  presupuestoArchivo?: (number | null) | Documento;
  preferidaAt?: string | null;
  avanceConfirmadoAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cotizacion-updates".
 */
export interface CotizacionUpdate {
  id: number;
  cotizacion: number | Cotizacione;
  autor: number | User;
  accion: 'mensaje' | 'estado' | 'presupuesto_borrador' | 'presupuesto_enviado';
  mensaje?: string | null;
  estadoAnterior?: ('enviada' | 'en_revision' | 'respondida' | 'cerrada' | 'cancelada') | null;
  estadoNuevo?: ('enviada' | 'en_revision' | 'respondida' | 'cerrada' | 'cancelada') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proyecto-drafts".
 */
export interface ProyectoDraft {
  id: number;
  user: number | User;
  refSlug?: string | null;
  titulo?: string | null;
  wizardStep?: number | null;
  tipo?: ('vivienda' | 'exterior') | null;
  subtipo?: string | null;
  superficie?: string | null;
  ubicacion?: string | null;
  plazo?: string | null;
  presupuesto?: string | null;
  terminaciones?:
    | {
        valor: string;
        id?: string | null;
      }[]
    | null;
  notas?: string | null;
  brief?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultas-proveedores".
 */
export interface ConsultasProveedore {
  id: number;
  nombre: string;
  email: string;
  rubro:
    | 'Aserradero'
    | 'Constructora'
    | 'Carpintería / CLT'
    | 'Estudio de arquitectura'
    | 'Proveedor de insumos'
    | 'Logística'
    | 'Otro';
  provincia:
    | 'Buenos Aires'
    | 'CABA'
    | 'Catamarca'
    | 'Chaco'
    | 'Chubut'
    | 'Córdoba'
    | 'Corrientes'
    | 'Entre Ríos'
    | 'Formosa'
    | 'Jujuy'
    | 'La Pampa'
    | 'La Rioja'
    | 'Mendoza'
    | 'Misiones'
    | 'Neuquén'
    | 'Río Negro'
    | 'Salta'
    | 'San Juan'
    | 'San Luis'
    | 'Santa Cruz'
    | 'Santa Fe'
    | 'Santiago del Estero'
    | 'Tierra del Fuego'
    | 'Tucumán';
  sitioWeb?: string | null;
  mensaje: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultas-contacto".
 */
export interface ConsultasContacto {
  id: number;
  nombre: string;
  email: string;
  organizacion?: string | null;
  asunto: string;
  mensaje: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documentos';
        value: number | Documento;
      } | null)
    | ({
        relationTo: 'empresas';
        value: number | Empresa;
      } | null)
    | ({
        relationTo: 'proyectos';
        value: number | Proyecto;
      } | null)
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null)
    | ({
        relationTo: 'biblioteca-recursos';
        value: number | BibliotecaRecurso;
      } | null)
    | ({
        relationTo: 'educacion-programas';
        value: number | EducacionPrograma;
      } | null)
    | ({
        relationTo: 'agenda-eventos';
        value: number | AgendaEvento;
      } | null)
    | ({
        relationTo: 'cotizaciones';
        value: number | Cotizacione;
      } | null)
    | ({
        relationTo: 'cotizacion-updates';
        value: number | CotizacionUpdate;
      } | null)
    | ({
        relationTo: 'proyecto-drafts';
        value: number | ProyectoDraft;
      } | null)
    | ({
        relationTo: 'consultas-proveedores';
        value: number | ConsultasProveedore;
      } | null)
    | ({
        relationTo: 'consultas-contacto';
        value: number | ConsultasContacto;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nombreCompleto?: T;
  role?: T;
  onboarded?: T;
  profileType?: T;
  telefono?: T;
  organizacion?: T;
  pais?: T;
  provincia?: T;
  ciudad?: T;
  intereses?:
    | T
    | {
        interes?: T;
        id?: T;
      };
  notas?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos_select".
 */
export interface DocumentosSelect<T extends boolean = true> {
  nombre?: T;
  empresa?: T;
  subidoPor?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "empresas_select".
 */
export interface EmpresasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  sector?: T;
  descripcion?: T;
  ubicacion?: T;
  tipoProveedor?: T;
  servicios?:
    | T
    | {
        servicio?: T;
        id?: T;
      };
  serviciosDetalle?:
    | T
    | {
        servicio?: T;
        detalle?: T;
        id?: T;
      };
  productos?:
    | T
    | {
        nombre?: T;
        descripcion?: T;
        imagen?: T;
        id?: T;
      };
  logo?: T;
  galeria?: T;
  sitioWeb?: T;
  anioFundacion?: T;
  empleados?: T;
  estado?: T;
  publicada?: T;
  user?: T;
  contacto?: T;
  telefono?: T;
  whatsapp?: T;
  documentos?: T;
  consentimientos?:
    | T
    | {
        terminosAceptados?: T;
        comunicacionesAceptadas?: T;
        version?: T;
        fechaConsentimiento?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proyectos_select".
 */
export interface ProyectosSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  resumen?: T;
  descripcion?: T;
  categoria?: T;
  ubicacion?: T;
  anio?: T;
  arquitecto?: T;
  constructora?: T;
  sistemaConstructivo?: T;
  impactoCarbono?: T;
  materiales?:
    | T
    | {
        material?: T;
        id?: T;
      };
  empresas?: T;
  portada?: T;
  galeria?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  resumen?: T;
  contenido?: T;
  categoria?: T;
  autor?: T;
  imagen?: T;
  destacada?: T;
  publicada?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "biblioteca-recursos_select".
 */
export interface BibliotecaRecursosSelect<T extends boolean = true> {
  titulo?: T;
  categoria?: T;
  archivo?: T;
  paginas?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educacion-programas_select".
 */
export interface EducacionProgramasSelect<T extends boolean = true> {
  titulo?: T;
  descripcion?: T;
  modalidad?: T;
  duracion?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agenda-eventos_select".
 */
export interface AgendaEventosSelect<T extends boolean = true> {
  titulo?: T;
  fecha?: T;
  lugar?: T;
  descripcion?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cotizaciones_select".
 */
export interface CotizacionesSelect<T extends boolean = true> {
  empresa?: T;
  solicitante?: T;
  tipoConsulta?: T;
  referencia?: T;
  descripcion?: T;
  cantidad?: T;
  plazo?: T;
  ubicacion?: T;
  presupuesto?: T;
  solicitanteNombre?: T;
  solicitanteEmail?: T;
  solicitanteTelefono?: T;
  solicitanteEmpresa?: T;
  estado?: T;
  respuesta?: T;
  respondidaAt?: T;
  presupuestoMonto?: T;
  presupuestoMoneda?: T;
  presupuestoValidezDias?: T;
  presupuestoPlazo?: T;
  presupuestoArchivo?: T;
  preferidaAt?: T;
  avanceConfirmadoAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cotizacion-updates_select".
 */
export interface CotizacionUpdatesSelect<T extends boolean = true> {
  cotizacion?: T;
  autor?: T;
  accion?: T;
  mensaje?: T;
  estadoAnterior?: T;
  estadoNuevo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proyecto-drafts_select".
 */
export interface ProyectoDraftsSelect<T extends boolean = true> {
  user?: T;
  refSlug?: T;
  titulo?: T;
  wizardStep?: T;
  tipo?: T;
  subtipo?: T;
  superficie?: T;
  ubicacion?: T;
  plazo?: T;
  presupuesto?: T;
  terminaciones?:
    | T
    | {
        valor?: T;
        id?: T;
      };
  notas?: T;
  brief?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultas-proveedores_select".
 */
export interface ConsultasProveedoresSelect<T extends boolean = true> {
  nombre?: T;
  email?: T;
  rubro?: T;
  provincia?: T;
  sitioWeb?: T;
  mensaje?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultas-contacto_select".
 */
export interface ConsultasContactoSelect<T extends boolean = true> {
  nombre?: T;
  email?: T;
  organizacion?: T;
  asunto?: T;
  mensaje?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-theme".
 */
export interface SiteTheme {
  id: number;
  colorPrimario?: string | null;
  colorSecundario?: string | null;
  logoClaro?: (number | null) | Media;
  logoOscuro?: (number | null) | Media;
  fuenteTitulos?: string | null;
  fuenteCuerpo?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-theme_select".
 */
export interface SiteThemeSelect<T extends boolean = true> {
  colorPrimario?: T;
  colorSecundario?: T;
  logoClaro?: T;
  logoOscuro?: T;
  fuenteTitulos?: T;
  fuenteCuerpo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}